MULLIKEN and LOEWDIN POPULATION ANALYSIS 

  atom#    atom      Mulliken charge       Loewdin charge
      1      Ba                 2.02                 1.76
      2      Ti                 0.96                 1.15
      3       O                -0.99                -0.96
      4       O                -0.99                -0.97
      5       O                -1.00                -0.97

          total                 0.00                 0.00
