MULLIKEN and LOEWDIN POPULATION ANALYSIS 

  atom#    atom      Mulliken charge       Loewdin charge
      1      Na                 0.67                 0.57
      2      Na                 0.67                 0.57
      3      Na                 0.67                 0.57
      4      Na                 0.67                 0.57
      5      Na                 0.70                 0.59
      6      Na                 0.70                 0.59
      7      Na                 0.70                 0.59
      8      Na                 0.70                 0.59
      9      Si                -0.70                -0.58
     10      Si                -0.70                -0.58
     11      Si                -0.70                -0.58
     12      Si                -0.70                -0.58
     13      Si                -0.68                -0.59
     14      Si                -0.68                -0.59
     15      Si                -0.68                -0.59
     16      Si                -0.68                -0.59

          total                 0.00                 0.00
